// p1-mfa-demo-react/client/src/App.jsx
import React, { useState } from 'react';
import logoSrc from './logo.png';

const styles = {
  header: {
    background: '#B8002F',
    padding: '12px 24px',
    display: 'flex',
    alignItems: 'center',
    marginBottom: 0,
  },
  logo: {
    height: 35,
    width: 'auto',
  },
  pageWrap: {
    padding: '32px 40px',
    maxWidth: 900,
    margin: '0 auto',
  },
};

function PageShell({ children }) {
  return (
    <div>
      <header style={styles.header}>
        <img src={logoSrc} style={styles.logo} alt="Ping Identity" />
      </header>
      <div style={styles.pageWrap}>
        {children}
      </div>
    </div>
  );
}

export default function App() {
  const [stage, setStage] = useState('login'); // login | mfa | done | error
  const [error, setError] = useState('');
  const [accessToken, setAccessToken] = useState('');

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [otp, setOtp] = useState('');

  async function handleLogin(e) {
    e.preventDefault();
    setError('');
    const resp = await fetch('/api/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ username, password }),
    });
    const json = await resp.json();
    if (json.status === 'COMPLETED') {
      setAccessToken(json.accessToken);
      setStage('done');
    } else if (json.status === 'MFA_REQUIRED') {
      setStage('mfa');
    } else {
      setError(json.message || 'Login failed');
      setStage('error');
    }
  }

  async function handleMfa(e) {
    e.preventDefault();
    setError('');
    const resp = await fetch('/api/mfa-verify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ otp }),
    });
    const json = await resp.json();
    if (json.status === 'COMPLETED') {
      setAccessToken(json.accessToken);
      setStage('done');
    } else {
      setError(json.message || 'MFA failed');
      setStage('error');
    }
  }

  function reset() {
    setStage('login');
    setError('');
    setUsername('');
    setPassword('');
    setOtp('');
    setAccessToken('');
  }

  if (stage === 'login') {
    return (
      <PageShell>
        <h2>Secure Login</h2>
        <form onSubmit={handleLogin}>
          <label>Username:</label><br />
          <input value={username} onChange={e => setUsername(e.target.value)} required /><br /><br />
          <label>Password:</label><br />
          <input type="password" value={password} onChange={e => setPassword(e.target.value)} required /><br /><br />
          <button type="submit">Log In</button>
        </form>
      </PageShell>
    );
  }

  if (stage === 'mfa') {
    return (
      <PageShell>
        <h2>Two-Factor Authentication</h2>
        <p>Please enter the verification code sent to your email.</p>
        <form onSubmit={handleMfa}>
          <label>MFA Code:</label><br />
          <input value={otp} onChange={e => setOtp(e.target.value)} required /><br /><br />
          <button type="submit">Verify</button>
        </form>
      </PageShell>
    );
  }

  if (stage === 'done') {
    return (
      <PageShell>
        <h2 style={{ color: 'green' }}>Login Successful!</h2>
        <p>You have securely authenticated. Here is your Access Token:</p>
        <pre style={{ background: '#eee', padding: 15, whiteSpace: 'pre-wrap', wordWrap: 'break-word' }}>{accessToken}</pre>
        <button onClick={reset}>Log Out</button>
      </PageShell>
    );
  }

  return (
    <PageShell>
      <h2 style={{ color: 'red' }}>Authentication Error</h2>
      <pre>{error}</pre>
      <button onClick={reset}>Try Again</button>
    </PageShell>
  );
}

// p1-mfa-demo-angular/client/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';

type Stage = 'login' | 'mfa' | 'done' | 'error';

interface ApiResponse {
  status: 'COMPLETED' | 'MFA_REQUIRED' | 'ERROR';
  accessToken?: string;
  message?: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div>
      <header style="background:#B8002F;padding:12px 24px;display:flex;align-items:center;margin-bottom:0;">
        <img [src]="logoSrc" style="height:35px;width:auto;" alt="Ping Identity">
      </header>
      <div style="padding:32px 40px;max-width:900px;margin:0 auto;">
    @switch (stage) {
      @case ('login') {
        <div>
          <h2>Secure Login</h2>
          <form (ngSubmit)="login()">
            <label>Username:</label><br>
            <input [(ngModel)]="username" name="username" required><br><br>
            <label>Password:</label><br>
            <input type="password" [(ngModel)]="password" name="password" required><br><br>
            <button type="submit">Log In</button>
          </form>
        </div>
      }
      @case ('mfa') {
        <div>
          <h2>Two-Factor Authentication</h2>
          <p>Please enter the verification code sent to your email.</p>
          <form (ngSubmit)="verifyMfa()">
            <label>MFA Code:</label><br>
            <input [(ngModel)]="otp" name="otp" required><br><br>
            <button type="submit">Verify</button>
          </form>
        </div>
      }
      @case ('done') {
        <div>
          <h2 style="color: green;">Login Successful!</h2>
          <p>You have securely authenticated. Here is your Access Token:</p>
          <pre style="background:#eee; padding:15px; white-space: pre-wrap; word-wrap: break-word;">{{ accessToken }}</pre>
          <button (click)="reset()">Log Out</button>
        </div>
      }
      @case ('error') {
        <div>
          <h2 style="color: red;">Authentication Error</h2>
          <pre>{{ error }}</pre>
          <button (click)="reset()">Try Again</button>
        </div>
      }
    }
      </div>
    </div>
  `,
})
export class AppComponent {
  private http = inject(HttpClient);

  logoSrc = 'assets/logo.png';
  stage: Stage = 'login';
  username = '';
  password = '';
  otp = '';
  accessToken = '';
  error = '';

  async login() {
    this.error = '';
    try {
      const resp = await firstValueFrom(
        this.http.post<ApiResponse>('/api/login',
          { username: this.username, password: this.password },
          { withCredentials: true }
        )
      );
      if (resp.status === 'COMPLETED') {
        this.accessToken = resp.accessToken || '';
        this.stage = 'done';
      } else if (resp.status === 'MFA_REQUIRED') {
        this.stage = 'mfa';
      } else {
        this.error = resp.message || 'Login failed';
        this.stage = 'error';
      }
    } catch (err: any) {
      this.error = err?.error?.message || err?.message || 'Login failed';
      this.stage = 'error';
    }
  }

  async verifyMfa() {
    this.error = '';
    try {
      const resp = await firstValueFrom(
        this.http.post<ApiResponse>('/api/mfa-verify',
          { otp: this.otp },
          { withCredentials: true }
        )
      );
      if (resp.status === 'COMPLETED') {
        this.accessToken = resp.accessToken || '';
        this.stage = 'done';
      } else {
        this.error = resp.message || 'MFA failed';
        this.stage = 'error';
      }
    } catch (err: any) {
      this.error = err?.error?.message || err?.message || 'MFA failed';
      this.stage = 'error';
    }
  }

  reset() {
    this.stage = 'login';
    this.username = '';
    this.password = '';
    this.otp = '';
    this.accessToken = '';
    this.error = '';
  }
}
