// p1-davinci-signon-angular/client/src/app/app.component.ts
/**
 * app.component.ts — Angular UI shell for the PingOne DaVinci Sign-On demo.
 *
 * All PingOne API calls are handled by the Express backend (server/index.js).
 * This standalone component collects username + password, POSTs to /api/run
 * via Angular's HttpClient, and renders the three-step results returned as JSON.
 *
 * Three render stages controlled by the `stage` property:
 *   idle    — shows the login form with username + password inputs.
 *   loading — shows a "Signing in…" message while the backend drives the flow.
 *   results — renders step cards using @for and the success/failure banner.
 *
 * The template uses Angular 18 built-in control flow (@switch / @case / @for /
 * @if) instead of *ngIf / *ngFor directives, which require CommonModule.
 * FormsModule is imported to enable [(ngModel)] two-way binding on form inputs.
 */
import { Component, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';

type Stage = 'idle' | 'loading' | 'results';

/** Matches the step object shape returned by the Express backend. */
interface StepResult {
  title: string;
  ok: boolean;
  detail: string;
  body: string;       // pretty-printed JSON response body, or empty string
  url: string;        // "METHOD https://full/url", or empty string
  collapsed: boolean; // if true, the response <details> starts closed
}

/** Top-level shape returned by POST /api/run. */
interface WorkflowResponse {
  success: boolean;
  steps: StepResult[];
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div>
      <header style="background:#B8002F;padding:12px 24px;display:flex;align-items:center;margin-bottom:0;">
        <img src="/logo.png" style="height:35px;width:auto;" alt="Ping Identity">
      </header>
      <div style="padding:32px 40px;max-width:900px;margin:0 auto;">
        <h2 style="margin-top:0;">DaVinci Sign-On Flow with PingOne Auth</h2>
        <p style="color:#555;margin-bottom:24px;">
          Sign in with credentials. The PingOne authorize endpoint hands the request to the
          assigned DaVinci flow policy; this app drives the flow to completion and exchanges
          the resulting code for a token.
        </p>

        @switch (stage) {
          @case ('idle') {
            <form (ngSubmit)="runWorkflow()" #loginForm="ngForm">
              <label style="font-size:14px;font-weight:600;">Username:</label><br>
              <input
                type="text"
                [(ngModel)]="username"
                name="username"
                required
                style="font-size:15px;padding:6px 8px;min-width:280px;margin-top:4px;"><br><br>
              <label style="font-size:14px;font-weight:600;">Password:</label><br>
              <input
                type="password"
                [(ngModel)]="password"
                name="password"
                required
                style="font-size:15px;padding:6px 8px;min-width:280px;margin-top:4px;"><br><br>
              <button
                type="submit"
                style="font-size:16px;padding:10px 24px;cursor:pointer;background:#E1003B;color:#fff;border:none;border-radius:4px;">
                Sign On
              </button>
            </form>
          }

          @case ('loading') {
            <div style="display:flex;align-items:center;gap:12px;color:#444;">
              <div style="
                width:22px;height:22px;
                border:3px solid #ccc;
                border-top-color:#E1003B;
                border-radius:50%;
                animation:spin 0.8s linear infinite;">
              </div>
              <span>Signing in&hellip;</span>
            </div>
            <style>
              @keyframes spin { to { transform: rotate(360deg); } }
            </style>
          }

          @case ('results') {
            @if (response) {
              <div style="
                padding:10px 14px;
                margin-bottom:20px;
                border-radius:4px;
                font-weight:600;
                background:{{ response.success ? '#e6f7e6' : '#fde8ea' }};
                color:{{ response.success ? '#0a7a0a' : '#b00020' }};">
                {{ response.success ? 'Sign-on completed successfully.' : 'Sign-on failed.' }}
              </div>

              @for (step of response.steps; track step.title) {
                <div style="
                  margin-top:16px;
                  border:1px solid #ddd;
                  border-radius:6px;
                  padding:14px 16px;
                  background:#fff;">

                  <h3 style="
                    margin:0 0 8px 0;
                    font-size:15px;
                    color:{{ step.ok ? '#0a7a0a' : '#b00020' }};">
                    {{ step.title }}&nbsp;{{ step.ok ? '(ok)' : '(failed)' }}
                  </h3>

                  @if (step.url) {
                    <div style="
                      font-family:monospace;
                      font-size:12px;
                      color:#555;
                      background:#f0f0f0;
                      padding:4px 8px;
                      border-radius:3px;
                      display:inline-block;
                      margin-bottom:8px;
                      word-break:break-all;">
                      {{ step.url }}
                    </div>
                  }

                  @if (step.detail) {
                    <p style="margin:6px 0 0 0;font-size:14px;color:#333;">{{ step.detail }}</p>
                  }

                  @if (step.body) {
                    <details [attr.open]="step.collapsed ? null : ''" style="margin-top:8px;">
                      <summary style="cursor:pointer;font-size:13px;color:#444;user-select:none;padding:2px 0;">
                        Response
                      </summary>
                      <pre style="
                        background:#f4f4f4;
                        padding:12px;
                        border-left:3px solid #888;
                        white-space:pre-wrap;
                        word-wrap:break-word;
                        margin:6px 0 0 0;
                        font-size:12px;
                        border-radius:0 4px 4px 0;">{{ step.body }}</pre>
                    </details>
                  }
                </div>
              }

              <div style="margin-top:24px;">
                <button
                  (click)="reset()"
                  style="font-size:14px;padding:8px 18px;cursor:pointer;border:1px solid #aaa;border-radius:4px;background:#f5f5f5;">
                  Sign In Again
                </button>
              </div>
            }
          }
        }
      </div>
    </div>
  `,
})
export class AppComponent {
  // HttpClient is provided via provideHttpClient(withFetch()) in main.ts.
  // inject() is the Angular 18 idiomatic approach for standalone components.
  private http = inject(HttpClient);

  stage: Stage = 'idle';
  response: WorkflowResponse | null = null;
  username = '';
  password = '';

  /**
   * Trigger the server-side DaVinci sign-on flow via POST /api/run.
   * The Angular dev-server proxy (proxy.conf.json) forwards /api/* to the
   * Express backend on port 3000, so no CORS configuration is needed in
   * development.
   * firstValueFrom converts the Observable returned by HttpClient.post into a
   * Promise, enabling straightforward async/await error handling.
   */
  async runWorkflow() {
    this.stage = 'loading';
    this.response = null;
    try {
      this.response = await firstValueFrom(
        this.http.post<WorkflowResponse>('/api/run', {
          username: this.username,
          password: this.password,
        })
      );
      this.stage = 'results';
    } catch (err: unknown) {
      // HttpClient wraps HTTP errors in an HttpErrorResponse; the actual message
      // may be in err.error.message (server JSON body) or err.message (network).
      const message =
        (err as { error?: { message?: string }; message?: string })?.error?.message ??
        (err as { message?: string })?.message ??
        'Request failed';
      this.response = {
        success: false,
        steps: [{
          title: 'Request failed',
          ok: false,
          detail: message,
          body: '',
          url: '',
          collapsed: false,
        }],
      };
      this.stage = 'results';
    }
  }

  /** Reset to the idle stage so the user can sign in again. */
  reset() {
    this.stage = 'idle';
    this.response = null;
    this.username = '';
    this.password = '';
  }
}

// p1-davinci-signon-react/client/src/App.jsx
/**
 * App.jsx — React UI for the PingOne DaVinci Sign-On workflow.
 *
 * All PingOne API calls are made by the Express backend (server/index.js).
 * This component shows a login form, POSTs credentials to /api/run, and
 * renders the step-by-step results returned as JSON.
 *
 * Three render stages:
 *   idle    — login form with username + password inputs
 *   loading — spinner / waiting message
 *   results — step cards + access token on success, or error detail on failure
 */
import React, { useState } from 'react';

const OK_COLOR  = '#0a7a0a';
const ERR_COLOR = '#b00020';

const styles = {
  h2: { marginBottom: 8 },
  description: { color: '#444', marginBottom: 24 },
  header: {
    background: '#B8002F',
    padding: '12px 24px',
    display: 'flex',
    alignItems: 'center',
    marginBottom: 0,
  },
  logo: {
    height: 35,
    width: 'auto',
  },
  pageWrap: {
    padding: '32px 40px',
    maxWidth: 900,
    margin: '0 auto',
  },
  label: {
    display: 'block',
    marginBottom: 4,
    fontSize: 14,
    color: '#333',
  },
  input: {
    fontSize: 15,
    padding: '6px 8px',
    minWidth: 280,
    marginBottom: 14,
    display: 'block',
    border: '1px solid #ccc',
    borderRadius: 3,
  },
  submitBtn: {
    fontSize: 16,
    padding: '10px 20px',
    cursor: 'pointer',
    background: '#E1003B',
    color: '#fff',
    border: 'none',
    borderRadius: 4,
  },
  loadingMsg: { color: '#555', fontStyle: 'italic', marginTop: 16 },
  banner: (ok) => ({
    padding: '10px 14px',
    marginBottom: 20,
    borderRadius: 4,
    background: ok ? '#e6f7e6' : '#fde8ea',
    color: ok ? OK_COLOR : ERR_COLOR,
    fontWeight: 600,
  }),
  tokenWrap: {
    marginTop: 16,
    marginBottom: 24,
  },
  tokenLabel: {
    fontSize: 13,
    color: '#555',
    marginBottom: 4,
  },
  tokenPre: {
    background: '#f4f4f4',
    padding: '10px 12px',
    borderLeft: '3px solid #888',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
    margin: 0,
    fontSize: 12,
  },
  card: {
    marginTop: 18,
    padding: '12px 16px',
    border: '1px solid #ddd',
    borderRadius: 4,
    background: '#fafafa',
  },
  cardTitle: (ok) => ({
    margin: '0 0 6px 0',
    color: ok ? OK_COLOR : ERR_COLOR,
    fontSize: 15,
    fontWeight: 600,
  }),
  urlBadge: {
    display: 'inline-block',
    fontFamily: 'monospace',
    fontSize: 12,
    color: '#555',
    background: '#f0f0f0',
    padding: '3px 8px',
    borderRadius: 3,
    marginBottom: 6,
    wordBreak: 'break-all',
  },
  detail: { margin: '4px 0 0 0', fontSize: 14, color: '#333' },
  summary: { cursor: 'pointer', fontSize: 13, color: '#444', userSelect: 'none', padding: '2px 0' },
  pre: {
    background: '#f4f4f4',
    padding: '10px 12px',
    borderLeft: '3px solid #888',
    whiteSpace: 'pre-wrap',
    wordWrap: 'break-word',
    margin: '6px 0 0 0',
    fontSize: 12,
  },
  againBtn: {
    marginTop: 24,
    fontSize: 15,
    padding: '8px 20px',
    cursor: 'pointer',
    background: '#555',
    color: '#fff',
    border: 'none',
    borderRadius: 4,
  },
};

/**
 * StepCard renders a single workflow step result as a card.
 *
 * collapsed=true (set by the backend for verbose responses) starts the
 * <details> element closed so the page does not overwhelm the reader.
 * The user can expand any card manually.
 */
function StepCard({ step }) {
  return (
    <div style={styles.card}>
      <h3 style={styles.cardTitle(step.ok)}>
        {step.title} {step.ok ? '(ok)' : '(failed)'}
      </h3>
      {step.url    && <div style={styles.urlBadge}>{step.url}</div>}
      {step.detail && <p style={styles.detail}>{step.detail}</p>}
      {step.body   && (
        <details open={!step.collapsed}>
          <summary style={styles.summary}>Response</summary>
          <pre style={styles.pre}>{step.body}</pre>
        </details>
      )}
    </div>
  );
}

export default function App() {
  // stage controls which view is shown: idle (login form), loading (spinner),
  // or results (step cards + token / error).
  const [stage,    setStage]    = useState('idle');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [result,   setResult]   = useState(null);

  /**
   * signOn — submits the credentials to the Express backend, which drives the
   * full three-step DaVinci sign-on flow and returns { success, steps[], accessToken? }.
   */
  async function signOn(e) {
    e.preventDefault();
    setStage('loading');
    try {
      const resp = await fetch('/api/run', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ username, password }),
      });
      const json = await resp.json();
      setResult(json);
      setStage('results');
    } catch (err) {
      // Network-level error (server unreachable, JSON parse failure, etc.).
      setResult({
        success: false,
        steps: [{
          title:     'Network error',
          ok:        false,
          detail:    err.message,
          body:      '',
          url:       '',
          collapsed: false,
        }],
      });
      setStage('results');
    }
  }

  function reset() {
    setStage('idle');
    setResult(null);
    setPassword('');
  }

  // ── idle: login form ──────────────────────────────────────────────────────
  if (stage === 'idle') {
    return (
      <div>
        <header style={styles.header}>
          <img src="/logo.png" style={styles.logo} alt="Ping Identity" />
        </header>
        <div style={styles.pageWrap}>
          <h2 style={styles.h2}>DaVinci Sign-On Flow with PingOne Auth</h2>
          <p style={styles.description}>
            Sign in with credentials. The PingOne authorize endpoint hands the
            request to the assigned DaVinci flow policy; this app drives the flow
            to completion and exchanges the resulting code for a token.
          </p>
          <form onSubmit={signOn}>
            <label style={styles.label} htmlFor="username">Username:</label>
            <input
              id="username"
              type="text"
              style={styles.input}
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              autoComplete="username"
            />
            <label style={styles.label} htmlFor="password">Password:</label>
            <input
              id="password"
              type="password"
              style={styles.input}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              autoComplete="current-password"
            />
            <button type="submit" style={styles.submitBtn}>Sign On</button>
          </form>
        </div>
      </div>
    );
  }

  // ── loading ───────────────────────────────────────────────────────────────
  if (stage === 'loading') {
    return (
      <div>
        <header style={styles.header}>
          <img src="/logo.png" style={styles.logo} alt="Ping Identity" />
        </header>
        <div style={styles.pageWrap}>
          <h2 style={styles.h2}>DaVinci Sign-On Flow with PingOne Auth</h2>
          <p style={styles.loadingMsg}>Signing in, please wait...</p>
        </div>
      </div>
    );
  }

  // ── results ───────────────────────────────────────────────────────────────
  return (
    <div>
      <header style={styles.header}>
        <img src="/logo.png" style={styles.logo} alt="Ping Identity" />
      </header>
      <div style={styles.pageWrap}>
        <h2 style={styles.h2}>Sign-On Result</h2>
        <div style={styles.banner(result.success)}>
          {result.success ? 'Sign-on successful.' : 'Sign-on failed.'}
        </div>

        {result.success && result.accessToken && (
          <div style={styles.tokenWrap}>
            <div style={styles.tokenLabel}>Access token:</div>
            <pre style={styles.tokenPre}>{result.accessToken}</pre>
          </div>
        )}

        {result.steps.map((step, i) => (
          <StepCard key={i} step={step} />
        ))}

        <button style={styles.againBtn} onClick={reset}>Sign In Again</button>
      </div>
    </div>
  );
}
