// p1-oidc-pkce-react/client/src/App.jsx
import React, { useState, useEffect } from 'react';

function StepCard({ card }) {
  return (
    <div style={{ marginTop: 18, padding: '14px 16px', border: '1px solid #ddd', borderRadius: 4 }}>
      <h3 style={{ margin: '0 0 6px 0', color: card.ok ? '#0a7a0a' : '#b00020' }}>
        {card.title} {card.ok ? '(ok)' : '(failed)'}
      </h3>
      {card.url && (
        <div style={{ fontFamily: 'monospace', fontSize: 13, color: '#555', background: '#eef', padding: '4px 8px', borderRadius: 3, margin: '6px 0', wordBreak: 'break-all' }}>
          {card.url}
        </div>
      )}
      {card.detail && <div dangerouslySetInnerHTML={{ __html: card.detail }} />}
      {card.body && (
        <details open={!card.collapsed} style={{ marginTop: 6 }}>
          <summary style={{ cursor: 'pointer', fontSize: 13, color: '#444', userSelect: 'none' }}>
            {card.collapsed ? 'Show response' : 'Hide'}
          </summary>
          <pre style={{ background: '#f4f4f4', padding: 12, borderLeft: '3px solid #888', whiteSpace: 'pre-wrap', wordBreak: 'break-all', margin: 0 }}>
            {card.body}
          </pre>
        </details>
      )}
    </div>
  );
}

function CardList({ cards }) {
  return <div>{cards.map((c, i) => <StepCard key={i} card={c} />)}</div>;
}

export default function App() {
  const [stage, setStage] = useState('start');
  const [prepareCards, setPrepareCards] = useState([]);
  const [authorizeURL, setAuthorizeURL] = useState('');
  const [callbackCards, setCallbackCards] = useState([]);
  const [refreshCards, setRefreshCards] = useState([]);
  const [hasRefreshToken, setHasRefreshToken] = useState(false);
  const [error, setError] = useState('');

  // On mount: check for callbackDone=1 in the URL
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('callbackDone') === '1') {
      setStage('loading-callback');
      fetch('/api/callback-result', { credentials: 'include' })
        .then(r => r.json())
        .then(data => {
          setPrepareCards(data.prepareCards || []);
          setCallbackCards(data.callbackCards || []);
          setHasRefreshToken(!!data.hasRefreshToken);
          history.replaceState(null, '', '/');
          setStage('callback-done');
        })
        .catch(err => {
          setError(err.message || 'Failed to load callback result');
          setStage('error');
        });
    } else if (params.get('callbackError') === '1') {
      history.replaceState(null, '', '/');
      setError('PingOne returned an error or state mismatch during callback. Check the server logs.');
      setStage('error');
    } else if (params.get('error') === 'nosession') {
      history.replaceState(null, '', '/');
      setError('No session found. Cookies may have been blocked.');
      setStage('error');
    }
  }, []);

  async function handleBeginLogin() {
    setStage('preparing');
    setError('');
    try {
      const resp = await fetch('/api/prepare', {
        method: 'POST',
        credentials: 'include',
      });
      if (!resp.ok) throw new Error(`Server error: ${resp.status}`);
      const data = await resp.json();
      setPrepareCards(data.prepareCards || []);
      setAuthorizeURL(data.authorizeURL || '');
      setStage('prepared');
    } catch (err) {
      setError(err.message || 'Failed to prepare PKCE artifacts');
      setStage('error');
    }
  }

  async function handleRefresh() {
    setStage('refreshing');
    setError('');
    try {
      const resp = await fetch('/api/refresh', {
        method: 'POST',
        credentials: 'include',
      });
      if (!resp.ok) throw new Error(`Server error: ${resp.status}`);
      const data = await resp.json();
      setRefreshCards(data.refreshCards || []);
      setStage('refresh-done');
    } catch (err) {
      setError(err.message || 'Failed to use refresh token');
      setStage('error');
    }
  }

  function handleStartOver() {
    setPrepareCards([]);
    setAuthorizeURL('');
    setCallbackCards([]);
    setRefreshCards([]);
    setHasRefreshToken(false);
    setError('');
    setStage('start');
  }

  if (stage === 'start') {
    return (
      <div>
        <h2>OIDC Authorization Code + PKCE (confidential client)</h2>
        <p>
          This sample walks through every artifact in the OIDC Authorization Code flow with PKCE so
          you can see exactly what each value is, how it&apos;s derived, and how it&apos;s validated.
        </p>
        <p>
          The client is <strong>confidential</strong> — the token endpoint is called with HTTP Basic
          auth (client ID + secret) AND the PKCE <code>code_verifier</code>.
        </p>
        <button
          onClick={handleBeginLogin}
          style={{ fontSize: 16, padding: '10px 20px', cursor: 'pointer' }}
        >
          Begin Login
        </button>
        <p style={{ color: '#666', fontSize: 13, marginTop: 30 }}>
          PingOne config required: OIDC Web App with PKCE Enforcement = REQUIRED, Token Endpoint Auth
          Method = Client Secret Basic, redirect URI = http://localhost:3000/callback
        </p>
      </div>
    );
  }

  if (stage === 'preparing') {
    return <p>Preparing PKCE artifacts...</p>;
  }

  if (stage === 'prepared') {
    return (
      <div>
        <h2>Step 1 — PKCE artifacts prepared</h2>
        <CardList cards={prepareCards} />
        <p style={{ marginTop: 24 }}>
          <a href={authorizeURL}>
            <button style={{ fontSize: 16, padding: '10px 20px', cursor: 'pointer' }}>
              Continue to PingOne →
            </button>
          </a>
        </p>
      </div>
    );
  }

  if (stage === 'loading-callback') {
    return <p>Loading callback results...</p>;
  }

  if (stage === 'callback-done') {
    return (
      <div>
        <h2>Prepare</h2>
        <CardList cards={prepareCards} />
        <h2 style={{ marginTop: 32 }}>Callback</h2>
        <CardList cards={callbackCards} />
        {hasRefreshToken && (
          <p style={{ marginTop: 24 }}>
            <button
              onClick={handleRefresh}
              style={{ fontSize: 16, padding: '10px 20px', cursor: 'pointer' }}
            >
              Use refresh token →
            </button>
          </p>
        )}
        <p style={{ marginTop: 20 }}>
          <a href="#" onClick={e => { e.preventDefault(); handleStartOver(); }}>Start over</a>
        </p>
      </div>
    );
  }

  if (stage === 'refreshing') {
    return <p>Refreshing...</p>;
  }

  if (stage === 'refresh-done') {
    return (
      <div>
        <h2>Refresh result</h2>
        <CardList cards={refreshCards} />
        <p style={{ marginTop: 20 }}>
          <a href="#" onClick={e => { e.preventDefault(); handleStartOver(); }}>Start over</a>
        </p>
      </div>
    );
  }

  // error stage
  return (
    <div>
      <h2 style={{ color: '#b00020' }}>Error</h2>
      <pre style={{ background: '#fff0f0', padding: 12, border: '1px solid #f00', borderRadius: 4 }}>
        {error}
      </pre>
      <button
        onClick={handleStartOver}
        style={{ fontSize: 16, padding: '10px 20px', cursor: 'pointer', marginTop: 12 }}
      >
        Start over
      </button>
    </div>
  );
}

// p1-oidc-pkce-angular/client/src/app/app.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { NgIf, NgFor } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';

interface Card {
  title: string;
  ok: boolean;
  url?: string | null;
  detail?: string | null;
  body?: string | null;
  collapsed?: boolean;
}

interface PrepareResponse {
  prepareCards: Card[];
  authorizeURL: string;
}

interface CallbackResultResponse {
  prepareCards: Card[];
  callbackCards: Card[];
  hasRefreshToken: boolean;
}

interface RefreshResponse {
  refreshCards: Card[];
}

type Stage =
  | 'start'
  | 'preparing'
  | 'prepared'
  | 'loading-callback'
  | 'callback-done'
  | 'refreshing'
  | 'refresh-done'
  | 'error';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [NgIf, NgFor],
  template: `
    @switch (stage) {

      @case ('start') {
        <div>
          <h2>OIDC Authorization Code + PKCE (confidential client)</h2>
          <p>
            This sample walks through every artifact in the OIDC Authorization Code flow with PKCE
            so you can see exactly what each value is, how it's derived, and how it's validated.
          </p>
          <p>
            The client is <strong>confidential</strong> — the token endpoint is called with HTTP
            Basic auth (client ID + secret) AND the PKCE <code>code_verifier</code>.
          </p>
          <button (click)="beginLogin()">Begin Login</button>
          <p style="color:#666; font-size:13px; margin-top:30px;">
            PingOne config required: OIDC Web App with PKCE Enforcement = REQUIRED,
            Token Endpoint Auth Method = Client Secret Basic,
            redirect URI = http://localhost:3000/callback
          </p>
        </div>
      }

      @case ('preparing') {
        <p>Preparing PKCE artifacts...</p>
      }

      @case ('prepared') {
        <div>
          <h3>Prepare</h3>
          @for (card of prepareCards; track $index) {
            <div style="margin-top: 18px; padding: 14px 16px; border: 1px solid #ddd; border-radius: 4px;">
              <h3 [style.color]="card.ok ? '#0a7a0a' : '#b00020'" style="margin: 0 0 6px 0">
                {{ card.title }} {{ card.ok ? '(ok)' : '(failed)' }}
              </h3>
              @if (card.url) {
                <div style="font-family: monospace; font-size: 13px; color: #555; background: #eef; padding: 4px 8px; border-radius: 3px; margin: 6px 0; word-break: break-all;">
                  {{ card.url }}
                </div>
              }
              @if (card.detail) {
                <div [innerHTML]="card.detail"></div>
              }
              @if (card.body) {
                <details [open]="!card.collapsed" style="margin-top: 6px;">
                  <summary style="cursor: pointer; font-size: 13px; color: #444; user-select: none;">
                    {{ card.collapsed ? 'Show response' : 'Hide' }}
                  </summary>
                  <pre style="background: #f4f4f4; padding: 12px; border-left: 3px solid #888; white-space: pre-wrap; word-break: break-all; margin: 0;">{{ card.body }}</pre>
                </details>
              }
            </div>
          }
          <p style="margin-top: 20px;">
            <button (click)="navigateToPingOne()">Continue to PingOne &#x2192;</button>
          </p>
        </div>
      }

      @case ('loading-callback') {
        <p>Loading callback results...</p>
      }

      @case ('callback-done') {
        <div>
          <h3>Prepare</h3>
          @for (card of prepareCards; track $index) {
            <div style="margin-top: 18px; padding: 14px 16px; border: 1px solid #ddd; border-radius: 4px;">
              <h3 [style.color]="card.ok ? '#0a7a0a' : '#b00020'" style="margin: 0 0 6px 0">
                {{ card.title }} {{ card.ok ? '(ok)' : '(failed)' }}
              </h3>
              @if (card.url) {
                <div style="font-family: monospace; font-size: 13px; color: #555; background: #eef; padding: 4px 8px; border-radius: 3px; margin: 6px 0; word-break: break-all;">
                  {{ card.url }}
                </div>
              }
              @if (card.detail) {
                <div [innerHTML]="card.detail"></div>
              }
              @if (card.body) {
                <details [open]="!card.collapsed" style="margin-top: 6px;">
                  <summary style="cursor: pointer; font-size: 13px; color: #444; user-select: none;">
                    {{ card.collapsed ? 'Show response' : 'Hide' }}
                  </summary>
                  <pre style="background: #f4f4f4; padding: 12px; border-left: 3px solid #888; white-space: pre-wrap; word-break: break-all; margin: 0;">{{ card.body }}</pre>
                </details>
              }
            </div>
          }

          <h3 style="margin-top: 32px;">Callback</h3>
          @for (card of callbackCards; track $index) {
            <div style="margin-top: 18px; padding: 14px 16px; border: 1px solid #ddd; border-radius: 4px;">
              <h3 [style.color]="card.ok ? '#0a7a0a' : '#b00020'" style="margin: 0 0 6px 0">
                {{ card.title }} {{ card.ok ? '(ok)' : '(failed)' }}
              </h3>
              @if (card.url) {
                <div style="font-family: monospace; font-size: 13px; color: #555; background: #eef; padding: 4px 8px; border-radius: 3px; margin: 6px 0; word-break: break-all;">
                  {{ card.url }}
                </div>
              }
              @if (card.detail) {
                <div [innerHTML]="card.detail"></div>
              }
              @if (card.body) {
                <details [open]="!card.collapsed" style="margin-top: 6px;">
                  <summary style="cursor: pointer; font-size: 13px; color: #444; user-select: none;">
                    {{ card.collapsed ? 'Show response' : 'Hide' }}
                  </summary>
                  <pre style="background: #f4f4f4; padding: 12px; border-left: 3px solid #888; white-space: pre-wrap; word-break: break-all; margin: 0;">{{ card.body }}</pre>
                </details>
              }
            </div>
          }

          @if (hasRefreshToken) {
            <p style="margin-top: 20px;">
              <button (click)="useRefreshToken()">Use refresh token &#x2192;</button>
            </p>
          }
          <p style="margin-top: 12px;">
            <button (click)="reset()">Start over</button>
          </p>
        </div>
      }

      @case ('refreshing') {
        <p>Refreshing...</p>
      }

      @case ('refresh-done') {
        <div>
          @for (card of refreshCards; track $index) {
            <div style="margin-top: 18px; padding: 14px 16px; border: 1px solid #ddd; border-radius: 4px;">
              <h3 [style.color]="card.ok ? '#0a7a0a' : '#b00020'" style="margin: 0 0 6px 0">
                {{ card.title }} {{ card.ok ? '(ok)' : '(failed)' }}
              </h3>
              @if (card.url) {
                <div style="font-family: monospace; font-size: 13px; color: #555; background: #eef; padding: 4px 8px; border-radius: 3px; margin: 6px 0; word-break: break-all;">
                  {{ card.url }}
                </div>
              }
              @if (card.detail) {
                <div [innerHTML]="card.detail"></div>
              }
              @if (card.body) {
                <details [open]="!card.collapsed" style="margin-top: 6px;">
                  <summary style="cursor: pointer; font-size: 13px; color: #444; user-select: none;">
                    {{ card.collapsed ? 'Show response' : 'Hide' }}
                  </summary>
                  <pre style="background: #f4f4f4; padding: 12px; border-left: 3px solid #888; white-space: pre-wrap; word-break: break-all; margin: 0;">{{ card.body }}</pre>
                </details>
              }
            </div>
          }
          <p style="margin-top: 20px;">
            <button (click)="reset()">Start over</button>
          </p>
        </div>
      }

      @case ('error') {
        <div>
          <h2 style="color: #b00020;">Error</h2>
          <p>{{ error }}</p>
          <button (click)="reset()">Start over</button>
        </div>
      }

    }
  `,
})
export class AppComponent implements OnInit {
  private http = inject(HttpClient);

  stage: Stage = 'start';
  prepareCards: Card[] = [];
  authorizeURL = '';
  callbackCards: Card[] = [];
  refreshCards: Card[] = [];
  hasRefreshToken = false;
  error = '';

  ngOnInit(): void {
    const params = new URLSearchParams(window.location.search);
    if (params.get('callbackDone') === '1') {
      this.stage = 'loading-callback';
      history.replaceState(null, '', window.location.pathname);
      this.loadCallbackResult();
    }
  }

  private async loadCallbackResult(): Promise<void> {
    try {
      const result = await firstValueFrom(
        this.http.get<CallbackResultResponse>('/api/callback-result', { withCredentials: true })
      );
      this.prepareCards    = result.prepareCards;
      this.callbackCards   = result.callbackCards;
      this.hasRefreshToken = result.hasRefreshToken;
      this.stage = 'callback-done';
    } catch (err: any) {
      this.error = err?.error?.error || err?.message || 'Failed to load callback result';
      this.stage = 'error';
    }
  }

  async beginLogin(): Promise<void> {
    this.error = '';
    this.stage = 'preparing';
    try {
      const result = await firstValueFrom(
        this.http.post<PrepareResponse>('/api/prepare', {}, { withCredentials: true })
      );
      this.prepareCards = result.prepareCards;
      this.authorizeURL = result.authorizeURL;
      this.stage = 'prepared';
    } catch (err: any) {
      this.error = err?.error?.error || err?.message || 'Failed to prepare login';
      this.stage = 'error';
    }
  }

  navigateToPingOne(): void {
    window.location.href = this.authorizeURL;
  }

  async useRefreshToken(): Promise<void> {
    this.error = '';
    this.stage = 'refreshing';
    try {
      const result = await firstValueFrom(
        this.http.post<RefreshResponse>('/api/refresh', {}, { withCredentials: true })
      );
      this.refreshCards = result.refreshCards;
      this.stage = 'refresh-done';
    } catch (err: any) {
      this.error = err?.error?.error || err?.message || 'Failed to refresh token';
      this.stage = 'error';
    }
  }

  reset(): void {
    this.stage = 'start';
    this.prepareCards = [];
    this.authorizeURL = '';
    this.callbackCards = [];
    this.refreshCards = [];
    this.hasRefreshToken = false;
    this.error = '';
  }
}
